version: '3.5'

# services: PHP + Nginx + Mysql + adminer
services:
  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./distr/:/var/www/html/
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx
  server:
    image: nginx
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "444:443"
    volumes:
      - ./distr/:/var/www/html/
      - ./app.conf:/etc/nginx/conf.d/app.conf:ro
    networks:
      - app-network

  #MySQL
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - app-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - app-network

#Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
