version: '3.5'

services:
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    restart: unless-stopped
    tty: true
    ports:
      - "3357:3306"
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql5
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./db-data-5:/var/lib/mysql/

  mysql8:
    image: mysql:8.0.21
    container_name: mysql8
    restart: unless-stopped
    tty: true
    ports:
      - "3380:3306"
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql8
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./db-data-8:/var/lib/mysql/

  mariadb101:
    image: mariadb:10.1
    container_name: mariadb101
    restart: unless-stopped
    tty: true
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mariadb101
    volumes:
      - ./db-data-10.1:/var/lib/mysql/

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
