version: '3.5'

services: 
    mysql5:
        image: mysql:5.7
        container_name: mysql5
        restart: unless-stopped
        tty: true
        ports:
            - "3305:3306"
        environment:
            MYSQL_DATABASE: distr
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql5
        volumes:
            - ./dbdata5:/var/lib/mysql/
        networks:
            - app-network
      
    mysql8:
        image: mysql:8.0.21
        container_name: mysql8
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: distr
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql8
        volumes:
            - ./dbdata8:/var/lib/mysql/
        networks:
        - app2-network

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8081:8080
        networks:
            - app-network
            - app2-network

networks:
    app-network:
        driver: bridge
    app2-network:
        driver: bridge
  
volumes:
    dbdata5:
        driver: local
    dbdata8:
        driver: local
