version: '3'
services:

  #PHP Service
  app:
    build:
      context: /srv/docker/php/php70
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
#    volumes:
#      - ./orfo/:/var/www/html
    networks:
      - app

  #Nginx Service
  webserver:
    image: httpd:2.4
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
#      - "444:443"
#    volumes:
#      - ./orfo/:/var/www/html
#      - /srv/docker/httpd/my-httpd.conf /usr/local/apache2/conf/httpd.conf
#      - /srv/docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app

  #MySQL Service
  db:
    image: mariadb:10.1
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - /srv/dbdata:/var/lib/mysql/
      - /srv/docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

#Docker Networks
networks:
  app:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

