version: '3.5'

services:      
  mysql8:
    image: mysql:8.0.21
    container_name: mysql8
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql8
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./db-data:/var/lib/mysql/
    # 172.17.0.1

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

volumes:
  dbdata8:
    driver: local
