version: '3.5'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./distr/:/var/www/html/
    networks:
      - net-1

  nginx-server:
    image: nginx
    container_name: nginx-server
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "444:443"
    volumes:
      - ./distr/:/var/www/html/
      - ./conf/app.conf:/etc/nginx/conf.d/app.conf:ro
    networks:
      - net-1

  mysql8:
    image: mysql:8.0.21
    container_name: mysql8
    restart: unless-stopped
    tty: true
    ports:
      - "3380:3306"
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql8
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/my.cnf
      - ./mysql8-data:/var/lib/mysql/
    networks:
      - net-1

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - net-1

networks:
  net-1:
    driver: bridge

volumes:
  mysql8-data:
    driver: local
