version: '3'
services:

  #php service
  app:
    build:
      context: .
      dockerfile: .
    image: php:7.3-fpm
    container_name: php-laravel-app
    restart: unless-stopped
    tty: true
    environment: 
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes: 
      - ./:/var/www
      - ./:/usr/local/etc/php/conf.d/local.ini

  #nginx service
  server:
    image: nginx:alpine
    container_name: nginx-laravel-app
    restart: unless-stopped
    tty: true
    ports: 
      - "7777:80"
    volumes: 
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #mysql service
  db:
    image: mysql:5.7.24
    container_name: mysql-laravel-app
    command: "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    tty: true
    ports: 
      - "7776:3306"
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes: 
      - ./mysql/data:/var/lib/mysql/
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf


#nginx app.conf
server {
  listen 80;
  index index.php index.html
  error_log /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;

  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+))$;

    fastcgi_pass app:9000; #link php

    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
  }

  location / {
    try_files $uri $uri/ /index.php?$query_string;
    gzip_static on;
  }
}
